#
# Copyright 2023, Colias Group, LLC
#
# SPDX-License-Identifier: BSD-2-Clause
#

# Match the rust toolchain with that in the rust-sel4 repository for best results.

[toolchain]
# channel = "nightly"
channel = "nightly-2024-11-18"
components = ["rustfmt", "rust-src","rust-analyzer"]
targets = ["riscv64gc-unknown-none-elf", "aarch64-unknown-none-softfloat"]
