/*
 * This file is autogenerated by rel4_config.
 */

pub const PHYS_BASE_RAW: usize = {{ physBase | format("0x{:x}") }};

/* INTERRUPTS */
{% for irq in kernel_irqs %}
/* {{ irq.desc }} */
// TODO: support feature select
pub const {{ irq.lable }}: usize = {{ irq.irq }};
{% endfor %}

/* KERNEL DEVICES */
